# Generated by Django 3.0.5 on 2021-01-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
                ('restaurant', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=100)),
                ('order', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('client_address', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
                ('deliveryperson', models.CharField(max_length=100)),
                ('expire_date', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
