# Generated by Django 3.0.5 on 2021-01-15 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='expire_date',
            new_name='expiration_date',
        ),
        migrations.RenameField(
            model_name='local',
            old_name='comuna',
            new_name='commune',
        ),
    ]
