# Generated by Django 3.0.5 on 2021-01-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='expiration_date',
            field=models.DateField(),
        ),
    ]
